= Create a Search Index Alias with the {page-ui-name}
:page-topic-type: guide
:page-ui-name: {ui-name}
:page-product-name: {product-name}
:description: Use a Search index alias to run a Search query across multiple buckets, scopes, or Search indexes. 

[abstract]
{description}

For more information about Search index aliases, see xref:index-aliases.adoc[].

== Prerequisites

* You have the Search Service enabled on a node in your operational cluster.
For more information about how to change Services on your operational cluster, see xref:cloud:clusters:modify-database.adoc[].

* You have created at least one Search index.
For more information, see xref:create-search-index-ui.adoc[].

* You have logged in to the Couchbase {page-ui-name}. 

== Procedure

To create a Search index alias with the {page-ui-name}: 

. On the *Operational Clusters* page, select the operational cluster where you want to work with the Search Service. 
. Click btn:[Create Search Alias].

== Next Steps

To customize a Search index, see xref:customize-index.adoc[].

To run a search and test the contents of your Search index or Search index alias, see xref:simple-search-ui.adoc[].